import os
import sys
import argparse

# Simple DB navigation (add/list/update/delete) for MySQL or Oracle
# Env vars:
#   MySQL: MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DB
#   Oracle: ORACLE_DSN, ORACLE_USER, ORACLE_PASSWORD


def connect_mysql():
    """Create a MySQL connection using env vars."""
    import mysql.connector
    return mysql.connector.connect(
        host=os.getenv("MYSQL_HOST", "localhost"),
        port=int(os.getenv("MYSQL_PORT", "3306")),
        user=os.getenv("MYSQL_USER", "root"),
        password=os.getenv("MYSQL_PASSWORD", ""),
        database=os.getenv("MYSQL_DB", "labdb"),
    )


def connect_oracle():
    """Create an Oracle connection using env vars."""
    import oracledb
    dsn = os.getenv("ORACLE_DSN", "localhost/orclpdb1")
    user = os.getenv("ORACLE_USER", "system")
    pwd = os.getenv("ORACLE_PASSWORD", "oracle")
    return oracledb.connect(user=user, password=pwd, dsn=dsn)


def ensure_table_mysql(conn):
    """Create table if missing (MySQL flavor)."""
    sql = (
        "CREATE TABLE IF NOT EXISTS books ("
        " id INT AUTO_INCREMENT PRIMARY KEY,"
        " title VARCHAR(200) NOT NULL,"
        " author VARCHAR(100) NOT NULL,"
        " price DECIMAL(10,2) NOT NULL)"
    )
    with conn.cursor() as cur:
        cur.execute(sql)
    conn.commit()


def ensure_table_oracle(conn):
    """Create table if missing (Oracle flavor)."""
    sql = (
        "BEGIN EXECUTE IMMEDIATE 'CREATE TABLE books ("
        " id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        " title VARCHAR2(200) NOT NULL,"
        " author VARCHAR2(100) NOT NULL,"
        " price NUMBER(10,2) NOT NULL)';"
        " EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;"
    )
    with conn.cursor() as cur:
        cur.execute(sql)
    conn.commit()


def add_book(conn, driver, title, author, price):
    """Insert a book row."""
    with conn.cursor() as cur:
        if driver == "mysql":
            cur.execute("INSERT INTO books(title, author, price) VALUES (%s,%s,%s)", (title, author, price))
        else:
            cur.execute("INSERT INTO books(title, author, price) VALUES (:1,:2,:3)", [title, author, price])
    conn.commit()


def list_books(conn, driver):
    """Print all books sorted by id."""
    with conn.cursor() as cur:
        cur.execute("SELECT id, title, author, price FROM books ORDER BY id")
        rows = cur.fetchall()
        for r in rows:
            print(r)


def update_book(conn, driver, book_id, price):
    """Update price for a book by id."""
    with conn.cursor() as cur:
        if driver == "mysql":
            cur.execute("UPDATE books SET price=%s WHERE id=%s", (price, book_id))
        else:
            cur.execute("UPDATE books SET price=:1 WHERE id=:2", [price, book_id])
    conn.commit()


def delete_book(conn, driver, book_id):
    """Delete a book by id."""
    with conn.cursor() as cur:
        if driver == "mysql":
            cur.execute("DELETE FROM books WHERE id=%s", (book_id,))
        else:
            cur.execute("DELETE FROM books WHERE id=:1", [book_id])
    conn.commit()


def main():
    p = argparse.ArgumentParser(description="Simple SQL DB navigation CLI")
    p.add_argument("--driver", choices=["mysql", "oracle"], required=True)
    sub = p.add_subparsers(dest="op", required=True)

    a = sub.add_parser("add")
    a.add_argument("title")
    a.add_argument("author")
    a.add_argument("price", type=float)

    sub.add_parser("list")

    u = sub.add_parser("update")
    u.add_argument("id", type=int)
    u.add_argument("price", type=float)

    d = sub.add_parser("delete")
    d.add_argument("id", type=int)

    args = p.parse_args()

    if args.driver == "mysql":
        conn = connect_mysql()
        ensure_table_mysql(conn)
    else:
        conn = connect_oracle()
        ensure_table_oracle(conn)

    try:
        if args.op == "add":
            add_book(conn, args.driver, args.title, args.author, args.price)
        elif args.op == "list":
            list_books(conn, args.driver)
        elif args.op == "update":
            update_book(conn, args.driver, args.id, args.price)
        elif args.op == "delete":
            delete_book(conn, args.driver, args.id)
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
